config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session
  resources :images, only: %i[index create new] do
    member do
      get :tweet
    end
  end
  namespace :oauth do
    get :callback
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  TITLE_LENGTH = 30

  validates :title, presence: true, length: { maximum: TITLE_LENGTH }
  validates :file, presence: { message: 'が選択されていません' }

  belongs_to :user

  attr_accessor :file

  def image_path
    Pathname.new('/upload').join(user.id.to_s).join(file_name).to_path
  end

  def upload_dir
    Rails.root.join('public', 'upload', user.id.to_s)
  end
end

app/models/session.rb
class Session
  include ActiveModel::Model

  attr_accessor :email, :password, :user

  validates :email, presence: true
  validates :password, presence: true
  validate :check_user, if: ->{ password.present? && email.present? }

  def user
    user = User.find_by(email: email)
    return unless user
    user if user.decrypt_password == password
  end

  private

    def check_user
      errors.add(:user_invalid, 'ユーザーが見つかりません') unless user
    end
end

app/models/user.rb
class User < ApplicationRecord
  before_save :password_encrypt

  has_many :images

  class << self
    def encrypt(password)
      crypt = ActiveSupport::MessageEncryptor.new(ENV['RAILS_KEY_MASTER'], 'aes-256-cbc')
      crypt.encrypt_and_sign(password)
    end
  end

  def password_encrypt
    self.password = User.encrypt(password)
  end

  def decrypt_password
    crypt = ActiveSupport::MessageEncryptor.new(ENV['RAILS_KEY_MASTER'], 'aes-256-cbc')
    crypt.decrypt_and_verify(password)
  end

  def correct_password?(password)
    decrypt_password == password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  def check_login
    redirect_to new_session_path if current_user.nil?
  end
end

app/controllers/images_controller.rb
require 'net/http'
require 'uri'
class ImagesController < ApplicationController
  before_action :check_login

  def index
    @images = current_user.images
  end

  def new
    @image = current_user.images.build
  end

  def create
    @image = current_user.images.build
    @image.assign_attributes(image_params)
    if @image.save
      redirect_to images_path
    else
      render :new
    end
  end

  def tweet
    uri = URI.parse('https://arcane-ravine-29792.herokuapp.com/api/tweets')
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true

    request = Net::HTTP::Post.new(uri.path)
    request['Content-Type'] = 'application/json'
    request['Authorization'] = "Bearer #{session[:access_token]}"

    image = Image.find(params[:id])
    request.body = JSON.generate({ text: image.title, url: "http://localhost:3000#{image.image_path}"})
    response = http.request(request)
  end

  private

    def image_params
      image_params = params.require(:image).permit(:title)
      file = params[:image][:file]
      if file.present?
        image = file.read
        file_name = save_image(image, file.original_filename)
        image_params.merge!(file: image, file_name: file_name)
        image_params.permit(:file, :file_name)
      end

      image_params
    end

    def save_image(image_file, origin_name)
      file_dir = @image.upload_dir
      FileUtils.mkdir_p(file_dir)
      file_name = "#{SecureRandom.hex(10)}_#{origin_name}"
      File.open(file_dir.join(file_name), 'w+b') do |file|
        file.write(image_file)
      end

      file_name
    end
end

app/controllers/oauth_controller.rb
require 'net/http'
require 'uri'
class OauthController < ApplicationController
  def callback
    if request.params.key?(:code)
      uri = URI.parse('https://arcane-ravine-29792.herokuapp.com/oauth/token')
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true

      request = Net::HTTP::Post.new(uri.path)
      request.set_form_data({
        code: request.params[:code], grant_type: :authorization_code,
        redirect_uri: Rails.application.routes.url_helpers.oauth_callback_url,
        client_id: ENV['OAUTH_CLIENT_ID'], client_secret: ENV['OAUTH_CLIENT_SECRET']
      })
      response = http.request(request)
      json = JSON.parse(response.body)
      session[:access_token] = json['access_token'] if json.key?('access_token')
    end
    redirect_to images_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @session = Session.new
  end

  def create
    @session = Session.new(email: params[:session][:email], password: params[:session][:password])
    return render :new unless @session.valid?
    user = @session.user
    if user
      session[:user_id] = user.email
      @current_user = user
      redirect_to images_path
    else
      render :new
    end
  end

  def show
    @session = Session.new
    render :new
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(email: session[:user_id])
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag  '/images/index', media: 'all', 'data-turbolinks-track': 'reload' %>
<% end %>
<main>
  <%= link_to "ログアウト", session_path, method: :delete %>
  <%= link_to  "MyTweetAppと連携", "https://arcane-ravine-29792.herokuapp.com/oauth/authorize?client_id=#{ENV['OAUTH_CLIENT_ID']}&response_type=code&redirect_uri=http://localhost:3000/oauth/callback" %>
  <h1>写真一覧</h1>
  <%= link_to '写真を新規にアップロード', new_image_path %>
  <ul class="imageList">
  <%@images.each do |image|%>
    <li class="imageList-inner">
      <section class="imageList-inner-item">
        <h2 class="imageList-inner-itemTitle"><%=image.title%></h2>
        <%=image_tag image.image_path, class: 'imageList-inner-itemImage'%>
        <%= link_to "tweet", tweet_image_path(id: image.id), remote: true %> 
      </section>
    </li>
  <%end%>
  </ul>
</main>

app/views/images/new.html.erb
<main class="mainContainer">
  <h1>写真アップロード</h1>
  <div class="mainContainer-inner">
    <ul>
      <%@image.errors.full_messages.each do |message|%>
        <li><%=message%></li>
      <%end%>
    </ul>
    <%=form_with model: @image, url: images_path, type: :post, local: true do |form|%>
      <section>
        <h2><%=form.label :title%></h2>
        <%=form.text_field :title%>
        <h2><%=form.label :file%></h2>
        <%=form.file_field :file%>
      </section>
      <ul class="buttons">
        <li><%=form.submit 'アップロード'%></li>
        <li><%= link_to "キャンセル", images_path %></li>
      </ul>
    <%end%>
    <%= render template: "layouts/application" %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head%>
  </head>

  <body>
    <%= yield %>
  </body>
</html>